# coding: utf-8

"""
    Chomp Food Database API Documentation

    __Important:__   - An __[API key](https://chompthis.com/api/)__ is required for access to this API.   - Get yours at __[https://chompthis.com/api](https://chompthis.com/api/)__.  -----  __Getting Started:__   - __[Subscribe](https://chompthis.com/api/#pricing)__ to the API.   - Scroll down and click the \"__Authorize__\" button.   - Enter your API key into the \"__value__\" input, click the \"__Authorize__\" button, then click the \"__Close__\" button.   - Scroll down to the section titled \"__default__\" and click on the API endpoint you wish to use.   - Click the \"__Try it out__\" button.   - Enter the information the endpoint requires.   - Click the \"__Execute__\" button.  __Example:__    - Branded Food: __[View example](https://raw.githubusercontent.com/chompfoods/examples/master/branded-food-response-object.json)__ API response object.   - Ingredient: __[View example](https://raw.githubusercontent.com/chompfoods/examples/master/ingredient-response-object.json)__ API response object.  -----  __How Do I Find My API Key?__   - Your API key was sent to the email address you used to create your subscription.   - You will also find your API key in the __[Client Center](https://chompthis.com/api/manage.php)__.   - _Read __[this article](https://desk.zoho.com/portal/chompthis/kb/articles/how-do-i-find-my-api-key)__ for more information._  ||| | ------- | -------- | | [Knowledge Base](https://desk.zoho.com/portal/chompthis/kb/chomp) | [Pricing](https://chompthis.com/api/) | | [Attribution](https://chompthis.com/api/docs/attribution.php) | [Cost Calculator](https://chompthis.com/api/cost-calculator.php) | | [Terms & License](https://chompthis.com/api/terms.php) | [Database Search](https://chompthis.com/api/lookup.php) | | [Support](https://chompthis.com/api/ticket-new.php) | [Query Builder](https://chompthis.com/api/build.php) | | [Client Center](https://chompthis.com/api/manage.php) | |   # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class BrandedFoodObjectDietLabelsVegetarian(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'is_compatible': 'bool',
        'compatibility_level': 'int',
        'confidence': 'int',
        'confidence_description': 'str'
    }

    attribute_map = {
        'name': 'name',
        'is_compatible': 'is_compatible',
        'compatibility_level': 'compatibility_level',
        'confidence': 'confidence',
        'confidence_description': 'confidence_description'
    }

    def __init__(self, name=None, is_compatible=None, compatibility_level=None, confidence=None, confidence_description=None):  # noqa: E501
        """BrandedFoodObjectDietLabelsVegetarian - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._is_compatible = None
        self._compatibility_level = None
        self._confidence = None
        self._confidence_description = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if is_compatible is not None:
            self.is_compatible = is_compatible
        if compatibility_level is not None:
            self.compatibility_level = compatibility_level
        if confidence is not None:
            self.confidence = confidence
        if confidence_description is not None:
            self.confidence_description = confidence_description

    @property
    def name(self):
        """Gets the name of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501

        Diet name  # noqa: E501

        :return: The name of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BrandedFoodObjectDietLabelsVegetarian.

        Diet name  # noqa: E501

        :param name: The name of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def is_compatible(self):
        """Gets the is_compatible of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501

        Boolean describing if this item is compatible with this diet  # noqa: E501

        :return: The is_compatible of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501
        :rtype: bool
        """
        return self._is_compatible

    @is_compatible.setter
    def is_compatible(self, is_compatible):
        """Sets the is_compatible of this BrandedFoodObjectDietLabelsVegetarian.

        Boolean describing if this item is compatible with this diet  # noqa: E501

        :param is_compatible: The is_compatible of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501
        :type: bool
        """

        self._is_compatible = is_compatible

    @property
    def compatibility_level(self):
        """Gets the compatibility_level of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501

        Numeric representation of how compatible this item is with this diet. Higher values indicate more compatibility  # noqa: E501

        :return: The compatibility_level of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501
        :rtype: int
        """
        return self._compatibility_level

    @compatibility_level.setter
    def compatibility_level(self, compatibility_level):
        """Sets the compatibility_level of this BrandedFoodObjectDietLabelsVegetarian.

        Numeric representation of how compatible this item is with this diet. Higher values indicate more compatibility  # noqa: E501

        :param compatibility_level: The compatibility_level of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501
        :type: int
        """

        self._compatibility_level = compatibility_level

    @property
    def confidence(self):
        """Gets the confidence of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501

        Boolean that indicates if we are confident in how this item is graded for this diet  # noqa: E501

        :return: The confidence of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501
        :rtype: int
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence):
        """Sets the confidence of this BrandedFoodObjectDietLabelsVegetarian.

        Boolean that indicates if we are confident in how this item is graded for this diet  # noqa: E501

        :param confidence: The confidence of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501
        :type: int
        """

        self._confidence = confidence

    @property
    def confidence_description(self):
        """Gets the confidence_description of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501

        Description of our confidence that this item was graded correctly  # noqa: E501

        :return: The confidence_description of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501
        :rtype: str
        """
        return self._confidence_description

    @confidence_description.setter
    def confidence_description(self, confidence_description):
        """Sets the confidence_description of this BrandedFoodObjectDietLabelsVegetarian.

        Description of our confidence that this item was graded correctly  # noqa: E501

        :param confidence_description: The confidence_description of this BrandedFoodObjectDietLabelsVegetarian.  # noqa: E501
        :type: str
        """

        self._confidence_description = confidence_description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BrandedFoodObjectDietLabelsVegetarian, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BrandedFoodObjectDietLabelsVegetarian):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
