# coding: utf-8

"""
    Chomp Food Database API Documentation

    __Important:__   - An __[API key](https://chompthis.com/api/)__ is required for access to this API. Get yours at __[https://chompthis.com/api](https://chompthis.com/api/)__.  -----  __Getting Started:__   - __[Subscribe](https://chompthis.com/api/#pricing)__ to the API.   - Scroll down and click the \"__Authorize__\" button.   - Enter your API key into the \"__value__\" input, click the \"__Authorize__\" button, then click the \"__Close__\" button.   - Scroll down to the section titled \"__default__\" and click on the API endpoint you wish to use.   - Click the \"__Try it out__\" button.   - Enter the information the endpoint requires.   - Click the \"__Execute__\" button.  __Example:__    - Branded Food: __[View example](https://raw.githubusercontent.com/chompfoods/examples/master/branded-food-response-object.json)__ API response object.   - Ingredient: __[View example](https://raw.githubusercontent.com/chompfoods/examples/master/ingredient-response-object.json)__ API response object.  -----  __How Do I Find My API Key?__   - Your API key was sent to the email address you used to create your subscription.   - You will also find your API key in the __[Client Center](https://chompthis.com/api/manage.php)__.   - _Read __[this article](https://desk.zoho.com/portal/chompthis/kb/articles/how-do-i-find-my-api-key)__ for more information._  ||| | ------- | -------- | | [Knowledge Base](https://desk.zoho.com/portal/chompthis/kb/chomp) | [Pricing](https://chompthis.com/api/) | | [Attribution](https://chompthis.com/api/docs/attribution.php) | [Cost Calculator](https://chompthis.com/api/cost-calculator.php) | | [Terms & License](https://chompthis.com/api/terms.php) | [Database Search](https://chompthis.com/api/lookup.php) | | [Support](https://chompthis.com/api/ticket-new.php) | [Query Builder](https://chompthis.com/api/build.php) | | [Client Center](https://chompthis.com/api/manage.php) | |   # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class BrandedFoodObjectPortions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'measurement_unit': 'str',
        'description': 'str',
        'modifier': 'str',
        'gram_weight': 'float',
        'data_points': 'int',
        'footnote': 'str'
    }

    attribute_map = {
        'measurement_unit': 'measurement_unit',
        'description': 'description',
        'modifier': 'modifier',
        'gram_weight': 'gram_weight',
        'data_points': 'data_points',
        'footnote': 'footnote'
    }

    def __init__(self, measurement_unit=None, description=None, modifier=None, gram_weight=None, data_points=None, footnote=None):  # noqa: E501
        """BrandedFoodObjectPortions - a model defined in Swagger"""  # noqa: E501
        self._measurement_unit = None
        self._description = None
        self._modifier = None
        self._gram_weight = None
        self._data_points = None
        self._footnote = None
        self.discriminator = None
        if measurement_unit is not None:
            self.measurement_unit = measurement_unit
        if description is not None:
            self.description = description
        if modifier is not None:
            self.modifier = modifier
        if gram_weight is not None:
            self.gram_weight = gram_weight
        if data_points is not None:
            self.data_points = data_points
        if footnote is not None:
            self.footnote = footnote

    @property
    def measurement_unit(self):
        """Gets the measurement_unit of this BrandedFoodObjectPortions.  # noqa: E501

        The unit used for measure (e.g. if mesure is 3 tsp, the unit is tsp)  # noqa: E501

        :return: The measurement_unit of this BrandedFoodObjectPortions.  # noqa: E501
        :rtype: str
        """
        return self._measurement_unit

    @measurement_unit.setter
    def measurement_unit(self, measurement_unit):
        """Sets the measurement_unit of this BrandedFoodObjectPortions.

        The unit used for measure (e.g. if mesure is 3 tsp, the unit is tsp)  # noqa: E501

        :param measurement_unit: The measurement_unit of this BrandedFoodObjectPortions.  # noqa: E501
        :type: str
        """

        self._measurement_unit = measurement_unit

    @property
    def description(self):
        """Gets the description of this BrandedFoodObjectPortions.  # noqa: E501

        Comments that provide more specificity on the measure. For example, for a pizza measure the dissemination text might be 1 slice is 1/8th of a 14 inch pizza.  # noqa: E501

        :return: The description of this BrandedFoodObjectPortions.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this BrandedFoodObjectPortions.

        Comments that provide more specificity on the measure. For example, for a pizza measure the dissemination text might be 1 slice is 1/8th of a 14 inch pizza.  # noqa: E501

        :param description: The description of this BrandedFoodObjectPortions.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def modifier(self):
        """Gets the modifier of this BrandedFoodObjectPortions.  # noqa: E501

        Qualifier of the measure (e.g. related to food shape or form) (e.g. melted, crushed, diced)  # noqa: E501

        :return: The modifier of this BrandedFoodObjectPortions.  # noqa: E501
        :rtype: str
        """
        return self._modifier

    @modifier.setter
    def modifier(self, modifier):
        """Sets the modifier of this BrandedFoodObjectPortions.

        Qualifier of the measure (e.g. related to food shape or form) (e.g. melted, crushed, diced)  # noqa: E501

        :param modifier: The modifier of this BrandedFoodObjectPortions.  # noqa: E501
        :type: str
        """

        self._modifier = modifier

    @property
    def gram_weight(self):
        """Gets the gram_weight of this BrandedFoodObjectPortions.  # noqa: E501

        The weight of the measure in grams  # noqa: E501

        :return: The gram_weight of this BrandedFoodObjectPortions.  # noqa: E501
        :rtype: float
        """
        return self._gram_weight

    @gram_weight.setter
    def gram_weight(self, gram_weight):
        """Sets the gram_weight of this BrandedFoodObjectPortions.

        The weight of the measure in grams  # noqa: E501

        :param gram_weight: The gram_weight of this BrandedFoodObjectPortions.  # noqa: E501
        :type: float
        """

        self._gram_weight = gram_weight

    @property
    def data_points(self):
        """Gets the data_points of this BrandedFoodObjectPortions.  # noqa: E501

        The number of observations on which the measure is based  # noqa: E501

        :return: The data_points of this BrandedFoodObjectPortions.  # noqa: E501
        :rtype: int
        """
        return self._data_points

    @data_points.setter
    def data_points(self, data_points):
        """Sets the data_points of this BrandedFoodObjectPortions.

        The number of observations on which the measure is based  # noqa: E501

        :param data_points: The data_points of this BrandedFoodObjectPortions.  # noqa: E501
        :type: int
        """

        self._data_points = data_points

    @property
    def footnote(self):
        """Gets the footnote of this BrandedFoodObjectPortions.  # noqa: E501

        Comments on any unusual aspects of the measure. Examples might includes caveats on the usage of a measure, or reasons why a measure gram weight is an unexpected value.  # noqa: E501

        :return: The footnote of this BrandedFoodObjectPortions.  # noqa: E501
        :rtype: str
        """
        return self._footnote

    @footnote.setter
    def footnote(self, footnote):
        """Sets the footnote of this BrandedFoodObjectPortions.

        Comments on any unusual aspects of the measure. Examples might includes caveats on the usage of a measure, or reasons why a measure gram weight is an unexpected value.  # noqa: E501

        :param footnote: The footnote of this BrandedFoodObjectPortions.  # noqa: E501
        :type: str
        """

        self._footnote = footnote

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BrandedFoodObjectPortions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BrandedFoodObjectPortions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
