# coding: utf-8

"""
    Chomp Food Database API Documentation

    __Important:__   - An __[API key](https://chompthis.com/api/)__ is required for access to this API.   - Get yours at __[https://chompthis.com/api](https://chompthis.com/api/)__.  -----  __Getting Started:__   - __[Subscribe](https://chompthis.com/api/#pricing)__ to the API.   - Scroll down and click the \"__Authorize__\" button.   - Enter your API key into the \"__value__\" input, click the \"__Authorize__\" button, then click the \"__Close__\" button.   - Scroll down to the section titled \"__default__\" and click on the API endpoint you wish to use.   - Click the \"__Try it out__\" button.   - Enter the information the endpoint requires.   - Click the \"__Execute__\" button.  __Example:__    - Branded Food: __[View example](https://raw.githubusercontent.com/chompfoods/examples/master/branded-food-response-object.json)__ API response object.   - Ingredient: __[View example](https://raw.githubusercontent.com/chompfoods/examples/master/ingredient-response-object.json)__ API response object.  -----  __How Do I Find My API Key?__   - Your API key was sent to the email address you used to create your subscription.   - You will also find your API key in the __[Client Center](https://chompthis.com/api/manage.php)__.   - _Read __[this article](https://desk.zoho.com/portal/chompthis/kb/articles/how-do-i-find-my-api-key)__ for more information._  ||| | ------- | -------- | | [Knowledge Base](https://desk.zoho.com/portal/chompthis/kb/chomp) | [Pricing](https://chompthis.com/api/) | | [Attribution](https://chompthis.com/api/docs/attribution.php) | [Cost Calculator](https://chompthis.com/api/cost-calculator.php) | | [Terms & License](https://chompthis.com/api/terms.php) | [Database Search](https://chompthis.com/api/lookup.php) | | [Support](https://chompthis.com/api/ticket-new.php) | [Query Builder](https://chompthis.com/api/build.php) | | [Client Center](https://chompthis.com/api/manage.php) | |   # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class BrandedFoodObjectCountryDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'english_speaking': 'int',
        'non_english_speaking': 'int'
    }

    attribute_map = {
        'english_speaking': 'english_speaking',
        'non_english_speaking': 'non_english_speaking'
    }

    def __init__(self, english_speaking=None, non_english_speaking=None):  # noqa: E501
        """BrandedFoodObjectCountryDetails - a model defined in Swagger"""  # noqa: E501
        self._english_speaking = None
        self._non_english_speaking = None
        self.discriminator = None
        if english_speaking is not None:
            self.english_speaking = english_speaking
        if non_english_speaking is not None:
            self.non_english_speaking = non_english_speaking

    @property
    def english_speaking(self):
        """Gets the english_speaking of this BrandedFoodObjectCountryDetails.  # noqa: E501

        The number of countries where English is the country's primary language  # noqa: E501

        :return: The english_speaking of this BrandedFoodObjectCountryDetails.  # noqa: E501
        :rtype: int
        """
        return self._english_speaking

    @english_speaking.setter
    def english_speaking(self, english_speaking):
        """Sets the english_speaking of this BrandedFoodObjectCountryDetails.

        The number of countries where English is the country's primary language  # noqa: E501

        :param english_speaking: The english_speaking of this BrandedFoodObjectCountryDetails.  # noqa: E501
        :type: int
        """

        self._english_speaking = english_speaking

    @property
    def non_english_speaking(self):
        """Gets the non_english_speaking of this BrandedFoodObjectCountryDetails.  # noqa: E501

        The number of countries where English is not the country's primary language  # noqa: E501

        :return: The non_english_speaking of this BrandedFoodObjectCountryDetails.  # noqa: E501
        :rtype: int
        """
        return self._non_english_speaking

    @non_english_speaking.setter
    def non_english_speaking(self, non_english_speaking):
        """Sets the non_english_speaking of this BrandedFoodObjectCountryDetails.

        The number of countries where English is not the country's primary language  # noqa: E501

        :param non_english_speaking: The non_english_speaking of this BrandedFoodObjectCountryDetails.  # noqa: E501
        :type: int
        """

        self._non_english_speaking = non_english_speaking

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BrandedFoodObjectCountryDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BrandedFoodObjectCountryDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
